name: "olab"
description: "OpenLab at SAIC"
baseurl: /olab-io.github.io
url: "http://localhost:4000"
paginate: 10
markdown: rdiscount
permalink: pretty
pygments: true

prose:
  rooturl: '_posts'
  siteurl: 'http://localhost:4000'
  relativeLinks: 'http://localhost:4000/links.jsonp'
  media: 'media'
  metadata:
    _posts:
      - name: "category"
        field:
          element: "hidden"
          value: "projects"
      - name: "layout"
        field:
          element: "hidden"
          value: "projects"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "splash"
        field:
          element: "text"
          label: "Splash image"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Open Source"
              value: "open_source"
            - name: "Art"
              value: "art"
            - name: "openFrameworks"
              value: "openframeworks"
            - name: "otherTag"
              value: "othertag"
